# Use the latest 2.1 version of CircleCI pipeline process engine.

version: 2.1

# Define a job to be invoked later in a workflow.

jobs:
  save_hello_world_output:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    docker:
      - image: circleci/node:13.8.0
    # Add steps to the job
    working_directory: /tmp
    steps:
      - run: echo "Hello World!!!" > output.txt
      - persist_to_workspace:
          paths:
            - /tmp/output.txt

  print_output_file:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    docker:
      - image: circleci/node:13.8.0
    # Add steps to the job
    working_directory: /tmp
    steps:
      - attach_workspace:
          at: /tmp
      - run: cat /tmp/output.txt

# Orchestrate jobs using workflows

workflows:
  myworkflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires: 
            - save_hello_world_output
