# Use the latest 2.1 version of CircleCI pipeline process engine.

version: 2.1

commands:
  print_pipeline_id:
    description: "A simple command to print the pipeline id"
    parameters:
      to:
        type: env_var_name
    steps:
      - run: echo pipeline_id <<parameters.to>>

jobs:
  myjob:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    docker:
      - image: "cimg/base:stable"
    # Add steps to the job
    steps:
      - print_pipeline_id:
          to : ${CIRCLE_WORKFLOW_ID}

# Orchestrate jobs using workflows
workflows:
  myworkflow:
    jobs:
      - myjob